const HELP = {

  clientsStatus: { title: 'Stav klienta', text: 'Označuje aktuální stav práce s klientem. Aktivní klient je dále podporován, ukončený již v projektu nepokračuje, rozpracovaný nemá dokončené vstupní údaje nebo zatím není plně zařazen.' },
  clientsEntryDate: { title: 'Datum vstupu do projektu', text: 'Datum, od kterého je klient zapojen do projektu a od kdy se jeho podpora započítává do evidence.' },
  clientsExitDate: { title: 'Datum výstupu z projektu', text: 'Vyplňte při ukončení spolupráce s klientem. Pokud klient pokračuje v podpoře, ponechte pole prázdné.' },
  clientsDisadvantage: { title: 'Typ znevýhodnění', text: 'Vyberte hlavní znevýhodnění relevantní pro monitorovací údaje projektu. Pokud údaj není známý nebo klient nespadá do uvedených kategorií, zvolte odpovídající obecnou možnost.' },
  clientsEmployment: { title: 'Postavení na trhu práce', text: 'Vyberte stav klienta platný při vstupu do projektu, případně podle aktuálních monitorovacích pravidel projektu.' },
  clientsEducation: { title: 'Dosažené vzdělání', text: 'Vyberte nejvyšší dosažené vzdělání klienta podle monitorovacích údajů.' },
  clientsNote: { title: 'Poznámka', text: 'Interní poznámka ke klientovi. Uvádějte pouze informace důležité pro práci v projektu nebo evidenci. Nepište citlivé údaje, které nejsou pro podporu klienta nezbytné.' },
  aiDescription: { title: 'Popis', text: 'Stručně popište, co bylo v rámci aktivity řešeno. Zaměřte se na podstatné téma, potřebu klienta, průběh řešení nebo důležité okolnosti.' },
  aiOutcome: { title: 'Výsledek', text: 'Popište, k čemu aktivita vedla. Například zda bylo něco vyjasněno, domluveno, předáno, zajištěno nebo zda zatím výsledek nenastal.' },
  aiNextSteps: { title: 'Navazující krok', text: 'Uveďte, co má následovat dál, kdo za to odpovídá a případně do kdy. Pokud další krok není potřeba, napište „Bez návaznosti“.' },
  supportSpecific_contactPlace: { title: 'Místo depistáže', text: 'Vyberte prostředí, ve kterém byl klient nebo potenciální klient vyhledán či kontaktován.' },
  supportSpecific_contactMethod: { title: 'Způsob kontaktu', text: 'Uveďte, jak ke kontaktu došlo. Rozlišujte aktivní oslovení pracovníkem, doporučení jiné instituce, podnět veřejnosti nebo situaci, kdy klient oslovil službu sám.' },
  supportSpecific_cooperationInterest: { title: 'Zájem o další spolupráci', text: 'Označte, zda klient projevil zájem pokračovat ve spolupráci. Pokud zatím není rozhodnutý, zvolte „nerozhodnut“.' },
  supportSpecific_physicalSignedFiled: { title: 'Zápis fyzicky podepsán a založen', text: 'Zaškrtněte pouze tehdy, pokud byl zápis k depistáži podepsán fyzicky a založen do klientské dokumentace. Po zaškrtnutí se elektronická pole Popis, Výsledek a Navazující krok nevyplňují.' },
  supportSpecific_mappedAreas: { title: 'Další zjištěné oblasti', text: 'Označte další oblasti, které byly při mapování identifikovány jako významné. Nejde o hlavní oblast podpory, ale o související zjištění.' },
  supportSpecific_risks: { title: 'Rizika', text: 'Vyberte míru rizika podle závažnosti zjištěné situace. Posuzujte zejména dopad na stabilitu klienta, bydlení, bezpečí, příjem, zdraví nebo péči o děti.' },
  supportSpecific_clientResources: { title: 'Zdroje klienta', text: 'Popište, o co se klient může opřít. Například vlastní schopnosti, rodinu, bydlení, příjem, podporující osoby, služby nebo motivaci řešit situaci.' },
  supportSpecific_clientNeeds: { title: 'Potřeby klienta', text: 'Popište hlavní potřeby, které ze šetření vyplynuly. Zaměřte se na to, co je třeba řešit pro stabilizaci situace klienta.' },
  supportSpecific_providedInformation: { title: 'Poskytnuté informace', text: 'Uveďte, jaké informace byly klientovi předány. Zaměřte se na věcný obsah poradenství, ne na dlouhý přepis rozhovoru.' },
  supportSpecific_recommendedProcedure: { title: 'Doporučený postup', text: 'Popište, jaký další postup byl klientovi doporučen. Uveďte konkrétní kroky, služby, instituce nebo dokumenty, pokud byly doporučeny.' },
  supportSpecific_fieldWorkPlace: { title: 'Místo výkonu', text: 'Vyberte místo, kde terénní práce skutečně proběhla.' },
  supportSpecific_visitPurpose: { title: 'Účel návštěvy', text: 'Vyberte hlavní účel návštěvy. Pokud měla návštěva více důvodů, zvolte ten, který byl pro aktivitu nejdůležitější.' },
  supportSpecific_accompanimentPlace: { title: 'Kam doprovod proběhl', text: 'Vyberte instituci, službu nebo místo, kam byl klient doprovázen.' },
  supportSpecific_accompanimentPurpose: { title: 'Účel doprovodu', text: 'Stručně popište, proč byl doprovod potřebný a co mělo být v rámci doprovodu řešeno.' },
  supportSpecific_accompanimentResult: { title: 'Výsledek doprovodu', text: 'Vyberte, zda se věc podařilo vyřídit, vyřídit jen částečně, nevyřídit nebo zda byl domluven další termín.' },
  supportSpecific_crisisType: { title: 'Typ krize', text: 'Vyberte hlavní typ krizové situace. Pokud se krize týká více oblastí, zvolte tu, která byla v daný okamžik nejzávažnější.' },
  supportSpecific_urgency: { title: 'Míra akutnosti', text: 'Vyberte míru naléhavosti podle toho, jak rychle bylo nutné situaci řešit a jak závažné bylo riziko pro klienta nebo jeho okolí.' },
  supportSpecific_measures: { title: 'Přijatá opatření', text: 'Uveďte pouze opatření, která byla skutečně provedena nebo domluvena. Nevkládejte plánovaná opatření, pokud k nim zatím nedošlo.' },
  supportSpecific_followupHelp: { title: 'Předání návazné pomoci', text: 'Popište, komu nebo kam byl klient předán, případně jaká návazná pomoc mu byla zprostředkována.' },
  supportSpecific_contactedFollowupServices: { title: 'Kontaktovaná návazná služba', text: 'Vyberte službu nebo instituci, která byla v rámci řešení skutečně kontaktována. Pokud kontakt neproběhl, zvolte „nebyla kontaktována“.' },
  supportSpecific_evaluationReason: { title: 'Důvod vyhodnocení/ukončení', text: 'Vyberte hlavní důvod, proč byla spolupráce vyhodnocena nebo ukončena.' },
  supportSpecific_achievedProgress: { title: 'Dosažený posun', text: 'Označte, zda u klienta došlo k posunu ve vztahu k řešené situaci nebo stanovenému cíli.' },
  supportSpecific_unresolvedAreas: { title: 'Nedořešené oblasti', text: 'Popište oblasti, které zůstávají nevyřešené nebo vyžadují další podporu.' },
  supportSpecific_recommendation: { title: 'Doporučení', text: 'Uveďte doporučený další postup po vyhodnocení nebo ukončení podpory.' },
  networkDescription: { title: 'Popis síťové aktivity', text: 'Stručně popište obsah jednání nebo aktivity sítě. Zaměřte se na projednaná témata, účel kontaktu a důležité okolnosti.' },
  actorName: { title: 'Název subjektu', text: 'Uveďte název organizace, instituce nebo subjektu, který je součástí partnerské sítě nebo je pro síť osloven.' },
  actorType: { title: 'Typ aktéra', text: 'Vyberte oblast nebo roli subjektu v síti. Údaj slouží k přehledu o složení partnerské sítě.' },
  actorContactName: { title: 'Kontaktní osoba', text: 'Uveďte osobu, se kterou projekt v daném subjektu jedná nebo která je za spolupráci relevantní.' },
  actorContactRole: { title: 'Funkce', text: 'Uveďte pracovní pozici nebo roli kontaktní osoby v organizaci.' },
  actorPhoneEmail: { title: 'Telefon / E-mail', text: 'Doplňte kontaktní údaje používané pro komunikaci s aktérem. Pokud údaj není známý, pole ponechte prázdné.' },
  clientsCaseNeed: { title: 'Potřeba case managementu', text: 'Zvolte Ano, pokud klient potřebuje koordinovanou podporu více služeb nebo institucí. Poté doplňte datum zahájení a důvod.' },
  clientsCaseSince: { title: 'Začátek case managementu', text: 'Datum, od kterého je klient veden v režimu case managementu.' },
  clientsCaseReason: { title: 'Důvod case managementu', text: 'Stručně a věcně popište, proč klient potřebuje koordinaci podpory.' },
  clientsAiSummary: { title: 'AI souhrn zakázky', text: 'Vytvoří pracovní souhrn z klientské osy a evidovaných podpor. Výsledek vždy zkontrolujte.' },
  clientsDriveFolder: { title: 'Složka klienta', text: 'Při uložení klienta založí složku se třemi pracovními podsložkami, monitorovacím listem a projektově správnou smlouvou a souhlasem.' },
  clientsSupportHours: { title: 'Čas podpory', text: 'Součet vychází z uložených záznamů a počítá se přesně v minutách. U výkonů se používá interval OD–DO; u individuálního plánu jeho uložená délka.' },
  iprSituation: { title: 'Popis situace', text: 'Popište výchozí situaci klienta, jeho zdroje, omezení, potřeby a podstatné bariéry stručně a věcně. Toto pole je povinné.' },
  iprGoals: { title: 'Cíle plánu', text: 'Každý cíl obsahuje popis, akční kroky a termín. Uložené cíle se nabízejí v zápisech jako vazba Cíl IP.' },
  iprGoalEvaluation: { title: 'Hodnocení cíle', text: 'Po označení cíle jako splněného doplňte slovní vyhodnocení. Používá se také při kontrole plnění cílů.' },
  iprFinalEvaluation: { title: 'Závěrečné vyhodnocení', text: 'Zobrazí se po splnění a vyhodnocení všech cílů. Shrňte výsledek celého plánu.' },
  aiGoalLink: { title: 'Cíl IP', text: 'Vyberte související cíl individuálního plánu. Pokud podpora na plán nenavazuje, použijte Jednorázovou zakázku.' },
  aiTime: { title: 'Čas podpory', text: 'Zadejte skutečný čas OD a DO. Trvání se vypočítá automaticky a započítává se do hodin podpory. Čas DO musí být pozdější.' },
  aiDelivery: { title: 'Forma poskytování', text: 'Vyberte ambulantní, terénní nebo telefonní formu. Pole je pro zápis individuální podpory povinné.' },
  aiSupportType: { title: 'Typ podpory', text: 'Vyberte skutečný druh poskytnuté podpory. Podle volby se mohou zobrazit další specifická pole.' },
  aiSupportArea: { title: 'Oblast podpory', text: 'Vyberte hlavní řešenou oblast. Údaj se používá při vyhodnocování projektových cílů a sociálního začlenění.' },
  aiSpecific: { title: 'Specifická pole', text: 'Pole odpovídají zvolenému typu podpory. Uvádějte pouze skutečně zjištěné nebo provedené činnosti.' },
  aiCasePartners: { title: 'Zapojení aktéři', text: 'Vyberte skutečně zapojené partnery z registru nebo doplňte další osobu ručně.' },
  aiGenerate: { title: 'AI návrh', text: 'Vytvoří pracovní návrh z vyplněných polí. Před uložením jej vždy věcně zkontrolujte a případně upravte.' },
  aiSave: { title: 'Uložení dokumentu', text: 'Uloží strukturovaný záznam i finální text do evidence, klientské osy a Google Sheetu. Chybějící povinná pole se zobrazí pod tlačítkem.' },
  aiOutput: { title: 'Výstup dokumentu', text: 'Toto je finální text ukládaný do evidence. Můžete jej vytvořit pomocí AI nebo napsat a upravit ručně.' },
  networkType: { title: 'Typ síťové aktivity', text: 'Vyberte skutečný typ aktivity. Údaj se ukládá do evidence a používá v přehledech a exportech.' },
  networkPlace: { title: 'Místo setkání', text: 'Vyberte přednastavené místo nebo doplňte jiné konkrétní místo jednání.' },
  networkAttendees: { title: 'Přítomné osoby', text: 'Vyberte pouze skutečně přítomné osoby. U porady jsou dostupné také role realizačního týmu.' },
  networkOutput: { title: 'Výstup zápisu', text: 'Finální text síťového zápisu. Používá se v uložené evidenci i v exportech.' },
  actorOrigin: { title: 'Zapojení aktéra', text: 'Rozlišuje stávajícího, nově zapojeného a potenciálního aktéra. Potenciální aktér bez doložené aktivity se do spolupracujících partnerů nepočítá.' },
  actorDate: { title: 'Datum zapojení', text: 'Vyplňuje se u nově zapojeného aktéra a pomáhá určit, zda byl partner zapojen v průběhu projektu.' },
  dashboardPeriod: { title: 'Vykazované období', text: 'Omezuje záznamy používané pro výpočty hodin, indikátorů, cílů, rizik a partnerské sítě.' },
  dashboardExport: { title: 'Export klientů a podpory', text: 'Exportuje základní monitorovací údaje a souhrn podpory pro další zpracování. Nejde o úplnou klientskou dokumentaci.' },
  dashboardZor: { title: 'Texty pro ZOR', text: 'Připraví anonymní pracovní texty podle právního aktu pro KA01, společný text KA02 členěný na a) Case management a b) Koordinace a síťování služeb, KA03 a pomocí AI také text k rovným příležitostem žen a mužů a nediskriminaci. Filtry klíčové aktivity a pracovníka výstup ZOR neomezují.' },
  dashboard600: { title: 'Indikátor 600 000', text: 'Počítá klienty se 40 a více hodinami podpory, kteří mají kompletní monitorovací údaje.' },
  dashboard670: { title: 'Indikátor 670 102', text: 'Počítá klienty s podporou nad 0 a pod 40 hodin, kteří mají minimální registrační údaje.' },
  dashboardLongGoals: { title: 'Dlouhodobé cíle', text: 'U klientů se 40 a více hodinami vyžaduje započtení vazbu výkonu na konkrétní splněný a slovně vyhodnocený cíl IP.' },
  dashboardShortSecurity: { title: 'Sociální zabezpečení', text: 'Započítá krátkodobě podpořeného klienta s doloženým výsledkem podpory v oblasti bydlení, finance/dluhy, zaměstnání nebo práva/povinnosti.' },
  dashboardShortServices: { title: 'Přístup ke službám', text: 'Započítá krátkodobě podpořeného klienta s doloženým výsledkem podpory v oblasti zdraví, bezpečí, vzdělání nebo služby.' },
  dashboardShortParenting: { title: 'Rodičovské kompetence', text: 'Započítá krátkodobě podpořeného klienta s doloženým výsledkem podpory v oblasti rodina.' },
  dashboardInclusion: { title: 'Sociální začlenění', text: 'Započítá krátkodobě podpořeného klienta s podporou nejméně ve třech různých oblastech KA1 nebo KA2.' },
  dashboardPartners: { title: 'Partnerská síť', text: 'Počítají se jen partneři s doloženou aktivitou. Jednorázový partner má jednu aktivitu; aktivita za 90 dní vychází z posledního záznamu.' },
  dashboardRisks: { title: 'Kontrolní upozornění', text: 'Nejde o chyby aplikace, ale o údaje nebo situace, které mohou ohrozit správné vykazování projektu.' }
};

export { HELP };
